<?php

 return array (
  'adm_theme' => 'sb-admin-2-bs4',
  'enable_ads' => '1',
  'model' =>
  array (
    'amenity' => 'Modules\Blog\Models\Amenity',
    'article' => 'Modules\Blog\Models\Article',
    'bell_boy' => 'Modules\Food\Models\BellBoy',
    'blog' => 'Modules\Blog\Models\Blog',
    'booking' => 'Modules\Cart\Models\Booking',
    'cart' => 'Modules\Cart\Models\Cart',
    'cuisine' => 'Modules\Food\Models\Cuisine',
    'cuisine_cat' => 'Modules\Food\Models\CuisineCat',
    'customer' => 'Modules\Customer\Models\Customer',
    'event' => 'Modules\Blog\Models\Event',
    'forum_reply' => 'Modules\Forum\Models\ForumReply',
    'home' => 'Modules\Blog\Models\Home',
    'ingredient' => 'Modules\Food\Models\Ingredient',
    'ingredient_cat' => 'Modules\Food\Models\IngredientCat',
    'location' => 'Modules\Food\Models\Location',
    'my_rating' => 'Modules\Blog\Models\MyRating',
    'opening_hour' => 'Modules\Food\Models\OpeningHour',
    'page' => 'Modules\Blog\Models\Page',
    'photo' => 'Modules\Blog\Models\Photo',
    'place' => 'Modules\Blog\Models\Place',
    'post' => 'Modules\Blog\Models\Post',
    'privacy' => 'Modules\Blog\Models\Privacy',
    'profile' => 'Modules\Blog\Models\Profile',
    'rating' => 'Modules\Blog\Models\Rating',
    'recipe' => 'Modules\Food\Models\Recipe',
    'restaurant' => 'Modules\Food\Models\Restaurant',
    'restaurant_map' => 'Modules\Food\Models\RestaurantMap',
    'restaurant_owner' => 'Modules\Food\Models\RestaurantOwner',
    'restaurant_provider' => 'Modules\Food\Models\RestaurantProvider',
    'tag' => 'Modules\Blog\Models\Tag',
    'tip' => 'Modules\Food\Models\Tip',
    'translation' => 'Modules\Xot\Models\Translation',
    'user' => 'Modules\LU\Models\User',
    'waiter' => 'Modules\Food\Models\Waiter',
    'widget' => 'Modules\Xot\Models\Widget',
  ),
  'primary_lang' => 'it',
  'pub_theme' => 'sb-admin-2-bs4',
);
